### PR TITLE
Created the signup page

### PR DESCRIPTION
**Pull request by fordfocus14**
Created a signup page for test fork merge. This style will be changed later.

### CODE REVIEW

**Review by chris13524 — CHANGES_REQUESTED** [review]
Can you remove the `.DS_Store` files?

**Comment by TylerBrubaker** [comment]
Chris we will, this was more making sure he knew how to commit to a fork and create a pull request. The look and redundancies will be removed before it gets merged to the master.

**Comment by chris13524** [comment]
@TylerBrubaker Ok, then at that point let's do a squash merge to avoid noisy logs

**Comment by TylerBrubaker** [comment]
Sounds good @chris13524

**Pull request closed without merging**
